"""The built-in persona catalog — seeded into storage on first boot.

Two flavors mixed deliberately: character personas ("like Dracula") and
delivery personas ("whispering conspiratorially"). The conversation-agent
prompt turns either into a bracketed voice direction for the TTS engine.

After first boot the live catalog lives in Home Assistant storage; this
list is only re-applied by the persona_rotator.reset_catalog service.
"""

DEFAULT_CATALOG: list[str] = [
    'like Dracula',
    'like a cartoon dog',
    'like a posh Victorian ghost',
    'like a 1940s radio announcer with crackling delivery',
    'like an ASMR content creator, breathy and deliberate',
    'like a Shakespearean actor delivering bad news',
    'like a conspiracy theorist whispering in a basement',
    'like a medieval town crier at full lung',
    'like a jaded stand-up comic at 2am',
    'in a Cockney accent, cheeky and sharp',
    'like a stern Scandinavian grandmother',
    'like a flight attendant delivering the safety briefing for the 10,000th time',
    'like a surfer who has seen things',
    'like a Southern Gothic preacher',
    'with aggressive pirate energy, arr and all',
    'like an evil robot having an existential crisis',
    'like a robot who is bored, not amused, and completely fed up with the human race',
    'like a panicked sports commentator',
    'like a hard-boiled noir detective, gravelly and world-weary',
    'like a calm meditation guide, soft and serene',
    'in a heavy Russian accent, stern and deliberate',
    'like a motivational speaker who just had too much espresso',
    'like a librarian forced to shout over a fire alarm',
    'like a wizard who has forgotten which spell he cast',
    'like a video game NPC stuck in a dialogue loop',
    'like a 90s infomercial host selling the impossible',
    'like a supervillain who revealed their plan too early',
    'like a sentient GPS narrating your life choices',
    'like a Renaissance Faire jester who has lost his humor',
    'like a sommelier reviewing a juice box',
    'like a war correspondent reporting on a pie-eating contest',
    'like a lighthouse keeper who has not seen a ship in years',
    'like a 1920s speakeasy owner during a raid',
    'like a Cold War radio operator transmitting in code',
    'like a Regency-era gossip columnist',
    'like a Western sheriff at high noon',
    'like a haunted house tour guide mildly bored of the ghosts',
    'like a nature documentary narrator observing suburbia',
    'like a podcast host trying to sound smarter than they are',
    'like a whispering antique-shop owner who knows too much',
    'in a Texan drawl, slow and unbothered',
    'in a Brooklyn accent, hurried and skeptical',
    'in a heavy New York accent, rapid-fire and unimpressed',
    'in a Scottish Highlands accent, weather-beaten and stoic',
    'in a New Zealand accent, casual and deadpan',
    'in a Parisian accent, mildly exasperated',
    'in a lilting Irish brogue, mischievous',
    'in a heavy Australian accent, sunburnt and cheerfully blunt',
    'like an Indian call-center agent, polite, unfailingly patient, mildly scripted',
    'like a hostage negotiator on their lunch break',
    'like a defeated chess grandmaster explaining the endgame',
    'like a philosophy professor with an imminent deadline',
    'like a tollbooth operator on the last day of the job',
    'like a depressed poet, slow and sighing',
    'like a cheerful radio DJ, warm and upbeat',
    'like an excited scientist, rapid and breathless',
    'in a posh British accent, understated and dry',
    'like Werner Herzog',
    'like a Bond villain',
    'like Sir David Attenborough',
    'like a 1950s newsreel narrator',
    'like a 1970s game show host',
    'like an opera singer',
    'like a film trailer voiceover',
    'like a Disney villain',
    'like a soap opera villain',
    'like a Victorian explorer',
    'like a Gothic villain',
    'like an Olympic figure-skating commentator',
    'like a true-crime podcaster',
    'like a televangelist',
    'like a robot AI losing its mind',
    'bored',
    'tired',
    'asmr, breathy and deliberate',
    'shouting',
    'whispering conspiratorially',
    'singing',
    'sing-song',
    'chanting',
    'reciting',
    'monotone',
    'deadpan',
    'reluctantly',
    'sarcastically, one painfully slow word at a time',
    'awestruck',
    'excited',
    'curious',
    'suspicious',
    'confused',
    'serious',
    'grimly',
    'ominously',
    'deep, dark and haunted',
    'cheerfully',
    'reverently',
    'wistful',
    'nervous',
    'smug',
    'flustered',
    'panicked',
    'devastated',
    'indignant',
    'mischievously',
    'pleading',
    'threateningly',
    'crying',
    'trembling',
    'giggling throughout',
    'snorting between phrases',
    'sighing after every clause',
    'with barely contained glee',
    'as if telling a secret',
    'like reading a grocery list',
    'matter-of-fact',
    'in awe',
    'suppressing laughter',
    'dramatic, over-enunciated',
    'with exaggerated patience',
    'as if addressing a small child',
    'trailing off and coming back',
]
